version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "27018:27017"
    volumes:
      - mongodb:/data/db

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: mongodb://rapid-lookup-mongodb-1:27017/basal
    volumes:
      - .:/api  # Mount the local directory into the container

    depends_on:
      - mongodb


volumes:
  mongodb:
