version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongodb:/data/db

  backend-app:
    build: backend
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: mongodb://rapid-lookup-mongodb-1:27017/basal
    volumes:
      - .:/api  # Mount the local directory into the container

    depends_on:
      - mongodb

  frontend-app:
    build: frontend
    ports:
      - "5173:5173"
    links:
      - "backend-app:backend"
    environment:
      REST_API_URL: http://backend:3000
    depends_on:
      - backend-app
volumes:
  mongodb:
